[project]
name = "unit"
version = "0.1.0"
description = "System User Units tools"
readme = "README.md"
authors = [
    { name = "wlanboy", email = "wlanboy@githumb.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
unit = "unit:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright>=1.1.411",
]
